"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Form from "next/form";

export default function pricing() {


  return (
    <>
      <Head>
        <title>Icons Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome/>
      <main className="mian-text01 comon-content-div sapce-bm w-100 float-left">
         <div className="container">
         <h2 className="comon-cont-head"> FAQ </h2>
         <p className="col-lg-8 mt-3"> These terms of use govern the access, browsing and use of Iconsguru by their users 
                    the download and use of certain content owned by Icons Mind as well as the.  </p>
            <div className="accounding mt-4">
                <div className="accordion" id="accordionExample">
                  <div className="accordion-item">
                    <h2 className="accordion-header" id="headingOne">
                      <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          How to download?
                      </button>
                    </h2>
                    <div id="collapseOne" className="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                      <div className="accordion-body">
                            <p> Download the perfection and largest unique icons drawn by hand  </p>
                      </div>
                    </div>
                  </div>
                  <div className="accordion-item">
                    <h2 className="accordion-header" id="headingTwo">
                      <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                          How work the free licenece?
                      </button>
                    </h2>
                    <div id="collapseTwo" className="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                      <div className="accordion-body">
                      <p> Download the perfection and largest unique icons drawn by hand  </p>
                      </div>
                    </div>
                  </div>
                  <div className="accordion-item">
                    <h2 className="accordion-header" id="headingThree">
                      <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                          No able to upgrade?
                      </button>
                    </h2>
                    <div id="collapseThree" className="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                      <div className="accordion-body">
                      <p> Download the perfection and largest unique icons drawn by hand  </p>
                      </div>
                    </div>
                  </div>
                </div>
            </div>

            <p className="mt-4 have-text"> Have more questions? <Link href="/contact"> Clck to see Contact </Link>  </p>

         </div>
      </main>


      <Footer/>
    </>
  );
}
