"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Form from "next/form";

export default function whyus() {


  return (
    <>
      <Head>
        <title>Icons Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome/>
      <main className="float-start w-100 why-us01">
         <section className="tops-sections01 d-inline-block w-100">
            <div className="container">
                <div className="row row-cols-1 row-cols-lg-2">
                  <div className="col">
                      <div className="text-caraole-divb d-inline-block w-100">
                          <h2> Make money with <span className="d-block"> IconsGuru Affiliate Program </span> </h2>
                          <p className="col-9 mt-4"> Earn up to 20% in commissions for every customer you refer to us. </p>
                          <Link href="/icon" className="btn btn-expolre mt-2"> Start now </Link>
                      </div>
                  </div>
                  <div className="col">
                      <figure className="m-0 text-center d-block">
                          <Image loading="lazy" src="/pic.svg"
                                alt="iconsguru"
                                width={530}
                                height={390} />
                      </figure>
                  </div>
                </div>
            </div>
         </section>

         <section className="tops-sections01 next-why d-inline-block w-100">
            <div className="container">
                <div className="row row-cols-1 row-cols-lg-2">
                  <div className="col">
                      <figure className="m-0 text-start d-block">
                          <Image loading="lazy" src="/why-choose.svg"
                                alt="iconsguru"
                                width={530}
                                height={390} />
                      </figure>
                  </div>
                  <div className="col">
                      <div className="text-caraole-divb d-inline-block w-100">
                          <h2> Why Choose Us? </h2>
                          <div className="row row-cols-1 row-cols-lg-2 mt-4 gy-4 g-lg-4">
                             <div className="col">
                                <div className="comon-list01">
                                   <h3> <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(31,177,65,1)"><path d="M21 4V18.7215C21 18.9193 20.8833 19.0986 20.7024 19.1787L12 23.0313L3.29759 19.1787C3.11667 19.0986 3 18.9193 3 18.7215V4H1V2H23V4H21ZM8 12V14H16V12H8ZM8 8V10H16V8H8Z"></path></svg></span> Free & Premium 
                                   Icons </h3>
                                   <p className="mt-3"> It is a long established fact that a reader will be distracted by the readable content of a page. </p>
                                </div>
                             </div>
                             <div className="col">
                                <div className="comon-list01">
                                   <h3> <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(31,177,65,1)"><path d="M7 17H17V22H7V17ZM19 20V15H5V20H3C2.44772 20 2 19.5523 2 19V9C2 8.44772 2.44772 8 3 8H21C21.5523 8 22 8.44772 22 9V19C22 19.5523 21.5523 20 21 20H19ZM5 10V12H8V10H5ZM7 2H17C17.5523 2 18 2.44772 18 3V6H6V3C6 2.44772 6.44772 2 7 2Z"></path></svg></span> Multiple Formats Available </h3>
                                   <p className="mt-3"> It is a long established fact that a reader will be distracted by the readable content of a page. </p>
                                </div>
                             </div>
                             <div className="col">
                                <div className="comon-list01">
                                   <h3> <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(31,177,65,1)"><path d="M12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22H2L4.92893 19.0711C3.11929 17.2614 2 14.7614 2 12C2 6.47715 6.47715 2 12 2ZM16 13H8C8 15.2091 9.79086 17 12 17C14.2091 17 16 15.2091 16 13Z"></path></svg></span> Neat & Clean Design </h3>
                                   <p className="mt-3"> It is a long established fact that a reader will be distracted by the readable content of a page. </p>
                                </div>
                             </div>
                             <div className="col">
                                <div className="comon-list01">
                                   <h3> <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(31,177,65,1)"><path d="M4.7134 7.12811L4.46682 7.69379C4.28637 8.10792 3.71357 8.10792 3.53312 7.69379L3.28656 7.12811C2.84706 6.11947 2.05545 5.31641 1.06767 4.87708L0.308047 4.53922C-0.102682 4.35653 -0.102682 3.75881 0.308047 3.57612L1.0252 3.25714C2.03838 2.80651 2.84417 1.97373 3.27612 0.930828L3.52932 0.319534C3.70578 -0.106511 4.29417 -0.106511 4.47063 0.319534L4.72382 0.930828C5.15577 1.97373 5.96158 2.80651 6.9748 3.25714L7.69188 3.57612C8.10271 3.75881 8.10271 4.35653 7.69188 4.53922L6.93228 4.87708C5.94451 5.31641 5.15288 6.11947 4.7134 7.12811ZM18.2278 2.3713L13.2886 6.21289C9.34224 5.23923 5.55843 7.54646 4.5 11.4966C4.39826 11.8763 4.36647 12.262 4.33317 12.666C4.21829 14.0599 4.08554 15.6707 1 17.9966C3.5 19.4966 8 20.9984 11.5016 20.9984C14.8142 20.9984 17.8463 18.7896 18.7444 15.4377C19.0836 14.1719 19.0778 12.895 18.7847 11.7067L22.6253 6.76879C22.9349 6.3707 22.8997 5.80435 22.543 5.44774L19.5488 2.45355C19.1922 2.09694 18.6259 2.06168 18.2278 2.3713ZM16.8952 8.2852C16.8319 8.21952 16.7673 8.15494 16.7015 8.09149L15.5769 6.96685L18.7589 4.49198L20.5046 6.23774L18.0297 9.41972L16.8952 8.2852Z"></path></svg></span> Pofessionally Crafted Icons </h3>
                                   <p className="mt-3"> It is a long established fact that a reader will be distracted by the readable content of a page. </p>
                                </div>
                             </div>
                          </div>
                      </div>
                  </div>
                </div>
            </div>
         </section>

         <section className="darsk-sections d-inline-block w-100">
            <div className="container">
               <div className="row row-cols-1 row-cols-lg-2 align-items-center">
                   <div className="col">
                      <Image loading="lazy" src="/adf.svg"
                          alt="iconsguru"
                          width={371}
                          height={269} />
                   
                   </div>
                   <div className="col">
                      <div className="contents-div">
                          <h3 className="text-white"> Why you should join IconsGuru affiliate partner? </h3>
                          <p className="text-white mt-3"> Earn money and join the our Affiliate Program. This free to join, easy to use and a great way to make
                             money with your website. Earn a 20% commission on sales you generate. Monthly payouts 
                             via PayPal or Bank/Wire Transfer. </p>
                          <Link href="/icon" className="btn btn-st-bn mt-3"> Start now </Link>
                      </div>
                   </div>
               </div>
            </div>
         </section>

         <section className="value-sections d-inline-block w-100">
            <div className="container">

                <h3 className="text-center"> We say it straight </h3>
                <p className="col-lg-7 mx-auto text-center mt-3 mb-4"> At our core, we believe that great design starts with the right details—and icons play a powerful role in bringing that vision to life.</p>
               
                <div className="row row-cols-1 row-cols-lg-3 g-lg-5 gy-4 mt-2 mb-5">
                    <div className="col">
                        <div className="comon-crads text-center d-inline-block w-100">
                            <figure className="m-0">
                                <Image loading="lazy" src="/games1.svg"
                                alt="iconsguru"
                                width={263}
                                height={185} />
                            
                            </figure>
                            <h4 className="mt-3"> How to create you first icons? </h4>
                            <p className="mt-3"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                        </div>
                    </div>
                    <div className="col">
                        <div className="comon-crads text-center d-inline-block w-100">
                            <figure className="m-0">
                                <Image loading="lazy" src="/card2.svg"
                                alt="iconsguru"
                                width={263}
                                height={185} />
                            
                            </figure>
                            <h4 className="mt-3"> Best plugins for figma 2022  </h4>
                            <p className="mt-3"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                        </div>
                    </div>
                    <div className="col">
                        <div className="comon-crads text-center d-inline-block w-100">
                            <figure className="m-0">
                                <Image loading="lazy" src="/card3.svg"
                                alt="iconsguru"
                                width={263}
                                height={185} />
                            
                            </figure>
                            <h4 className="mt-3"> How to speed your work. </h4>
                            <p className="mt-3"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                        </div>
                    </div>
                </div>
            </div>
         </section>

      </main>

      <Footer/>
    </>
  );
}
