
import React from 'react';
import Footer from "../components/Footer";
import NavicationHome from "../components/NavicationHome";
import Head from "next/head";

export default function WhyUsPage() {
  return (
    <>
     <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome/>
    <div className="p-6 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-4">About Us</h1>
      <p className="mb-4">
        At IconsGuru, we believe in quality, creativity, and customer satisfaction. Whether you're a designer, developer, or business owner, our icon platform is built to support your vision.
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>Thousands of handcrafted icons</li>
        <li>Fast and easy-to-use interface</li>
        <li>Smart search with autocomplete</li>
        <li>Customization and downloads in SVG, PNG, WebP</li>
        <li>Dedicated support and continuous updates</li>
      </ul>
    </div>
    <Footer/>
    </>
  );
}
