"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import { useRouter } from "next/navigation";

export default function PlansPage() {
  const [plans, setPlans] = useState([]);
 const [user,setUser]=useState(null);
 const router = useRouter();
  useEffect(() => {
    fetch("https://iconsguru.ascinatetech.com/api/subscriptions")
      .then((res) => res.json())
      .then((data) => {
        if (data?.subscriptions) {
          setPlans(data.subscriptions);
        }
      })
      .catch((error) => {
        console.error("Error fetching plans:", error);
      });

      const storedUser=localStorage.getItem("user");
      const storedToken=localStorage.getItem("access_token");
      if(storedUser && storedToken){
        setUser({
          ...JSON.parse(storedUser),
          token: storedToken,
        });
      }

  }, []);

  const handleUpgrade = async (subscriptionId) =>{
    if (!user?.token){
      alert("Please login to upgrade your plan");
      router.push("/login");
      return;
    }
    try{
      const res= await fetch("https://iconsguru.ascinatetech.com/api/user/upgrade-subscription",{
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${user.token}`,
        },
        body: JSON.stringify({ subscription_id: subscriptionId }),
      });
      const data=await res.json();
      if(res.ok){
        alert("Subsription upgrade sucessfully!");
        const updatedUser= { ...user, subscription_id: subscriptionId};
        localStorage.setItem("user", JSON.stringify(updatedUser));
        setUser(updatedUser);
      }else{
        alert(data.message || "Upgrade failed");
      }
    }catch(err){
      confirm.error("Upgrade error:", err);
    }
  };

  return (
    <>
      <Head>
        <title>Pricing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome />
      <main className="pricing-pages-part float-start w-100">
        <div className="container mt-4">
          <h2 className="comon-heading-sub">Pricing</h2>
          <p className="sub-texr01"> Why you should upgrade your free plan? </p>

          <div className="col-lg-6">
            <div className="row gy-4 g-lg-4">
              {plans.map((plan) => (
                <div className="col-lg-4" key={plan.subscription_id}>
                  <div className="card months-div h-100">
                    <h2>{plan.name}</h2>
                    <h3 className="mt-3">
                      <strong>${parseFloat(plan.price).toFixed(2)}</strong>
                      <small> / {plan.duration}</small>
                    </h3>
                    <p>
                      {plan.icon_limit
                        ? `${plan.icon_limit} icons`
                        : "Unlimited icons"}
                      <br />
                      billed {plan.duration === "yearly" ? "per year" : "per month"}
                    </p>
                    <button className="btn btn-upgrade" onClick={() => handleUpgrade(plan.subscription_id)}>Upgrade plan now</button>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="faq-parts01 d-inline-block w-100">
            <h2 className="comon-heading-sub">FAQ </h2>
            <p className="sub-texr01"> These terms of use govern the access, browsing and use of Icons Mind by their users the download and use of
              certain content owned by Icons Mind as well as the.  </p>

            <div className="as-divbg mt-5 d-inline-block w-100">
              <div className="accordion" id="accordionExample">
                <div className="accordion-item">
                  <h2 className="accordion-header" id="headingOne">
                    <button className="accordion-button ps-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      How to download?
                    </button>
                  </h2>
                  <div id="collapseOne" className="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div className="accordion-body ps-0">
                      <p> incorporated under the laws of Poland and registered in the companies register of the National Court Register held by District. </p>
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                  <h2 className="accordion-header" id="headingTwo">
                    <button className="accordion-button collapsed ps-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      How work the free license?
                    </button>
                  </h2>
                  <div id="collapseTwo" className="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div className="accordion-body ps-0">
                      <p> incorporated under the laws of Poland and registered in the companies register of the National Court Register held by District. </p>
                    </div>
                  </div>
                </div>
                <div className="accordion-item">
                  <h2 className="accordion-header" id="headingThree">
                    <button className="accordion-button collapsed ps-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      No able to upgrade?
                    </button>
                  </h2>
                  <div id="collapseThree" className="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div className="accordion-body ps-0">
                      <p> incorporated under the laws of Poland and registered in the companies register of the National Court Register held by District. </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>


        </div>
      </main>

      <Footer />
    </>
  );
}
