"use client";
import { useState, useRef } from "react";
import Head from "next/head";

export default function canvas() {
  const [inputValue, setInputValue] = useState('');
  
  const handleChange = (e) => {
    setInputValue(e.target.value);
  };

  const [fontStyle, setFontStyle] = useState('normal');

  const handleStyleChange = (e) => {
    setFontStyle(e.target.value);
  };

  const [fontSize, setFontSize] = useState(24);

  const handleFontSizeChange = (e) => {
    const size = parseInt(e.target.value, 10);
    if (!isNaN(size)) {
      setFontSize(size);
    }
  };

    const [textColor, setTextColor] = useState('#000000');
  
    const handleColorChange = (e) => {
      setTextColor(e.target.value);
    };
    const [textAlign, setTextAlign] = useState('left');
    const handleAlignChange = (e) => {
      setTextAlign(e.target.value);
    };

    const [imageSrc, setImageSrc] = useState(null);

    const handleImageChange = (e) => {
      const file = e.target.files[0];
      if (file && file.type.startsWith('image/')) {
        const reader = new FileReader();
        reader.onloadend = () => {
          setImageSrc(reader.result); 
        };
        reader.readAsDataURL(file);
      } else {
        setImageSrc(null);
      }
    };


    const [imageeSrc, setImageeSrc] = useState(null);

    const handleImageuChange = (e) => {
      const file = e.target.files[0];
      if (file && file.type.startsWith('image/')) {
        const reader = new FileReader();
        reader.onloadend = () => {
          setImageeSrc(reader.result); 
        };
        reader.readAsDataURL(file); 
      } else {
        alert('Please upload a valid image file.');
      }
      
    };

    const [position, setPosition] = useState({ x: 100, y: 100 });
    const dragging = useRef(false);
    const offset = useRef({ x: 0, y: 0 });
  
    const handleMouseDown = (e) => {
      dragging.current = true;
      offset.current = {
        x: e.clientX - position.x,
        y: e.clientY - position.y,
      };
    };
  
    const handleMouseMove = (e) => {
      if (!dragging.current) return;
      setPosition({
        x: e.clientX - offset.current.x,
        y: e.clientY - offset.current.y,
      });
    };
  
    const handleMouseUp = () => {
      dragging.current = false;
    };
  

  return (
    <>
      <Head>
        <title>Icons Page - Canvas design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mian-text01 canvas-main-part sapce-bm w-100 float-left">
         <section className="container-fluid">

            <div className="main-divb">
              <div style={{ marginTop: '20px', fontWeight: 'bold' }}>
                    You typed: <h1 style={{
                    fontStyle: fontStyle === 'bold' ? 'normal' : fontStyle,
                    fontWeight: fontStyle === 'bold' ? 'bold' : 'normal', fontSize: `${fontSize}px`, color: textColor , textAlign , 
                    
                  }} > {inputValue} </h1> 
              </div>
              
                  <div style={{ marginTop: '20px' }}>
                    <h3>Preview:</h3>
                    <img 
                      src={imageSrc || 'icons_guru_logo.webp'}
                      alt="Preview"
                      style={{ maxWidth: '100%', height: 'auto' }}
                    />
                  </div>

                  <div style={{
          border: '2px dashed #aaa',
          width: '300px',
          height: '300px',
          textAlign: 'center',
          lineHeight: '300px',
          marginBottom: '20px',
        }}  role="tablist">
                    <img src={imageeSrc} alt="Uploaded preview" style={{ maxWidth: '100%', height: 'auto' }} data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" />
                  </div>

                  
                  <div
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      style={{ height: '100vh', width: '100vw', position: 'relative', overflow: 'hidden' }}
    >
      <img
        src="/your-image.jpg"
        onMouseDown={handleMouseDown}
        alt="Draggable"
        style={{
          position: 'absolute',
          left: position.x,
          top: position.y,
          width: 150,
          height: 'auto',
          cursor: 'move',
          userSelect: 'none',
        }}
      />
    </div>

                
            </div>

             <div className="canvas-parts05">
                <div className="filerts-divs p-0">
                    <div className="canvs-part-mainu d-flex align-items-start">
                      <div className="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        <button className="nav-link active" id="v-pills-home-tab" data-bs-toggle="pill" data-bs-target="#v-pills-home" type="button" role="tab" aria-controls="v-pills-home" aria-selected="true">
                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(0,0,0,1)"><path d="M20.4668 8.69379L20.7134 8.12811C21.1529 7.11947 21.9445 6.31641 22.9323 5.87708L23.6919 5.53922C24.1027 5.35653 24.1027 4.75881 23.6919 4.57612L22.9748 4.25714C21.9616 3.80651 21.1558 2.97373 20.7238 1.93083L20.4706 1.31953C20.2942 0.893489 19.7058 0.893489 19.5293 1.31953L19.2761 1.93083C18.8442 2.97373 18.0384 3.80651 17.0252 4.25714L16.308 4.57612C15.8973 4.75881 15.8973 5.35653 16.308 5.53922L17.0677 5.87708C18.0555 6.31641 18.8471 7.11947 19.2866 8.12811L19.5331 8.69379C19.7136 9.10792 20.2864 9.10792 20.4668 8.69379ZM2 4C2 3.44772 2.44772 3 3 3H14V5H4V19H20V11H22V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V4ZM7 8H17V11H15V10H13V14H14.5V16H9.5V14H11V10H9V11H7V8Z"></path></svg>
                          </span>
                           Text 
                        </button>
                        <button className="nav-link" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" 
                        aria-controls="v-pills-profile" aria-selected="false">
                            <span>
                             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(0,0,0,1)"><path d="M20.4668 8.69379L20.7134 8.12811C21.1529 7.11947 21.9445 6.31641 22.9323 5.87708L23.6919 5.53922C24.1027 5.35653 24.1027 4.75881 23.6919 4.57612L22.9748 4.25714C21.9616 3.80651 21.1558 2.97373 20.7238 1.93083L20.4706 1.31953C20.2942 0.893489 19.7058 0.893489 19.5293 1.31953L19.2761 1.93083C18.8442 2.97373 18.0384 3.80651 17.0252 4.25714L16.308 4.57612C15.8973 4.75881 15.8973 5.35653 16.308 5.53922L17.0677 5.87708C18.0555 6.31641 18.8471 7.11947 19.2866 8.12811L19.5331 8.69379C19.7136 9.10792 20.2864 9.10792 20.4668 8.69379ZM2 4C2 3.44772 2.44772 3 3 3H14V5H4V19H20V11H22V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V4ZM7 8H17V11H15V10H13V14H14.5V16H9.5V14H11V10H9V11H7V8Z"></path></svg>
                            </span>
                            Layout 
                        </button>
                        <button className="nav-link" id="v-pills-messages-tab" data-bs-toggle="pill" data-bs-target="#v-pills-messages" type="button" role="tab" aria-controls="v-pills-messages" aria-selected="false">
                            <span>
                             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(0,0,0,1)"><path d="M20.4668 8.69379L20.7134 8.12811C21.1529 7.11947 21.9445 6.31641 22.9323 5.87708L23.6919 5.53922C24.1027 5.35653 24.1027 4.75881 23.6919 4.57612L22.9748 4.25714C21.9616 3.80651 21.1558 2.97373 20.7238 1.93083L20.4706 1.31953C20.2942 0.893489 19.7058 0.893489 19.5293 1.31953L19.2761 1.93083C18.8442 2.97373 18.0384 3.80651 17.0252 4.25714L16.308 4.57612C15.8973 4.75881 15.8973 5.35653 16.308 5.53922L17.0677 5.87708C18.0555 6.31641 18.8471 7.11947 19.2866 8.12811L19.5331 8.69379C19.7136 9.10792 20.2864 9.10792 20.4668 8.69379ZM2 4C2 3.44772 2.44772 3 3 3H14V5H4V19H20V11H22V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V4ZM7 8H17V11H15V10H13V14H14.5V16H9.5V14H11V10H9V11H7V8Z"></path></svg>
                            </span>
                            Bkground
                        </button>
                        <button className="nav-link" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controls="v-pills-settings" aria-selected="false">
                            <span>
                             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32" fill="rgba(0,0,0,1)"><path d="M20.4668 8.69379L20.7134 8.12811C21.1529 7.11947 21.9445 6.31641 22.9323 5.87708L23.6919 5.53922C24.1027 5.35653 24.1027 4.75881 23.6919 4.57612L22.9748 4.25714C21.9616 3.80651 21.1558 2.97373 20.7238 1.93083L20.4706 1.31953C20.2942 0.893489 19.7058 0.893489 19.5293 1.31953L19.2761 1.93083C18.8442 2.97373 18.0384 3.80651 17.0252 4.25714L16.308 4.57612C15.8973 4.75881 15.8973 5.35653 16.308 5.53922L17.0677 5.87708C18.0555 6.31641 18.8471 7.11947 19.2866 8.12811L19.5331 8.69379C19.7136 9.10792 20.2864 9.10792 20.4668 8.69379ZM2 4C2 3.44772 2.44772 3 3 3H14V5H4V19H20V11H22V20C22 20.5523 21.5523 21 21 21H3C2.44772 21 2 20.5523 2 20V4ZM7 8H17V11H15V10H13V14H14.5V16H9.5V14H11V10H9V11H7V8Z"></path></svg>
                            </span>
                            Logo
                        </button>
                      </div>
                      <div className="tab-content" id="v-pills-tabContent">
                        <div className="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                            <div className="comon-div-mains">
                                <h5> Edit icon text </h5>

                                      <input 
                                        type="text" 
                                        value={inputValue} 
                                        onChange={handleChange} 
                                        placeholder="Type here..."
                                      />
  
                                      <div className="w-100">
                                        <select onChange={handleStyleChange} value={fontStyle}>
                                          <option value="normal">Normal</option>
                                          <option value="italic">Italic</option>
                                          <option value="oblique">Oblique</option>
                                          <option value="bold">Bold</option>
                                        </select>
                                      </div>

                                      <p> Size </p>
                                      <input 
                                        type="number" 
                                        onChange={handleFontSizeChange} 
                                        value={fontSize}
                                        placeholder="Enter font size in px" 
                                        min="10"
                                      />

                                      <p> Color </p>

                                      <input 
                                        type="color" 
                                        value={textColor} 
                                        onChange={handleColorChange}
                                      />

                                    <select value={textAlign} onChange={handleAlignChange}>
                                            <option value="left">Left</option>
                                            <option value="center">Center</option>
                                            <option value="right">Right</option>
                                            <option value="justify">Justify</option>
                                    </select>

                                    <p> Size </p>

                                    
                                
                            </div>
                        </div>
                        <div className="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">

                              <input type="file" accept="image/*" onChange={handleImageChange} />
                              <input 
                                type="file" 
                                accept="image/*" 
                                onChange={handleImageuChange} 
                                style={{ marginBottom: '20px' }}
                              />

                             

                        </div>
                        <div className="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
                        <div className="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
                      </div>
                    </div>
                    
                </div>
             </div>


         </section>
      </main>

    </>
  );
}
