"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Form from "next/form";

export default function canvas() {


  return (
    <>
      <Head>
        <title>Icons Page - Canvas design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mian-text01 canvas-main-part sapce-bm w-100 float-left">
         <section className="container-fluid">


             <div className="canvas-parts05">
                <div className="filerts-divs p-4">
                    <h5> Edit icon text </h5>
                </div>
             </div>


         </section>
      </main>

    </>
  );
}
