"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Form from "next/form";

export default function pricing() {


  return (
    <>
      <Head>
        <title>Icons Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome/>
      <section className="sub-banners d-inline-block w-100 float-start mt-2">
                <div className="container">
                    <div className="row align-items-center">
                      <div className="col-lg-6">
                          <h2> Privacy <br/>
                          Icons by Category </h2>
                          <p className="col-lg-8 mt-3"> The largest database of vector icons available for download
                          SVG, EPS, PSD and BASE 64 formats. </p>
                      </div>
                      
                    </div>
                </div>
      </section>


      <Footer/>
    </>
  );
}
