"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Form from "next/form";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome/>
      <main className="pricing-pages-part float-start w-100">
          <div className="container mt-4">
            <div className="row align-items-center">
                <div className="col-lg-9">
                   <h2 className="comon-heading-sub">Account</h2>
                   <p className="sub-texr01"> On this page you can see all your icons collections </p>
                </div>
                <div className="col-lg-3">
                    <button type="button" className="btn btn-upgrade"> 
                      <span> 
                           <Image loading="lazy" src="/upg.svg"
                                                   alt="iconsguru"
                                                   width={22}
                                                   height={22} />
                      </span> Upgrade to pro plan 
                    </button>
                </div>
            </div>
            

          <div className="comons-page-divs d-inline-block w-100">
              <div className="account-edits-mains mt-4">
                 <ul className="d-flex align-items-center">
                   <li>
                     <Link href='/profile' className="men-lis01"> Profile </Link>
                   </li>
                   <li>
                     <Link href='/password' className="men-lis01"> Password </Link>
                   </li>
                   <li>
                     <Link href='/myplan' className="men-lis01"> Plans </Link>
                   </li>
                   <li>
                     <Link href='/billing' className="men-lis01"> Billing </Link>
                   </li>
                   <li>
                     <Link href='/download' className="men-lis01"> Download history </Link>
                   </li>
                 </ul>

                 <div className="page-details-partsy d-inline-block w-100 pt-5">
                     <div className="row row-cols-1 row-cols-lg-2 align-items-center">
                        <div className="col">
                             <div className="form-section-parts01">
                                <Form>
                                   <div className="form-group">
                                      <label className="form-label"> Full name </label>
                                      <input type="text" className="form-control" placeholder="David Bowie" required/>
                                   </div>
                                   <div className="form-group">
                                      <label className="form-label"> Email address </label>
                                      <input type="text" className="form-control" placeholder="tal@adoric.com" required/>
                                   </div>
                                   <div className="form-group mt-2">
                                      <button type="submit" className="btn btn-updates"> Update </button>
                                   </div>
                                   <div className="d-flex align-items-center">
                                      <div className="form-check form-switch mt-3">
                                        <input className="form-check-input" type="checkbox" id="flexSwitchCheckDefault"/>
                                        <label className="form-check-label" >
                                          I wish to receive newsletters, promotions 
                                          and news <br/> from Iconguru company
                                        </label>
                                      </div>
                                   </div>
                                </Form>
                             </div>
                        </div>
                        <div className="col d-grid justify-content-center">
                             <div className="img-part-sections">
                                    <Image loading="lazy" src="/user.svg"
                                              alt="iconsguru"
                                              width={135}
                                              height={135} />
                             </div>
                        
                        </div>
                     </div>
                 </div>
              </div>
          </div>
            
          </div>
       </main>

      <Footer/>
    </>
  );
}
